teamdigitale/io-functions

lib/__tests__/created_message_queue_handler.test.ts
lib/controllers/__tests__/messages.test.ts
lib/controllers/messages.ts
lib/created_message_queue_handler.ts
lib/emailnotifications_queue_handler.ts
lib/models/__tests__/created_message_event.test.ts
lib/models/__tests__/message.test.ts
lib/models/created_message_event.ts
lib/models/message.ts
lib/models/notification.ts
lib/models/notification_event.ts
lib/models/profile.ts
lib/utils/documentdb_model.ts
lib/utils/documentdb_model_versioned.ts

This commit also decouples the storage of message content in the message
record from the CreateMessage API handler, moving it to the async create
message handles.

[#151262556] Save message content in inbox only if enabled in profile

---

Openapi/function.json

The route template separator character '/' cannot appear consecutively. It must be separated by either a parameter or a literal value.
Parameter name: routeTemplate. della funzione ($Openapi)

fix: error in route definition

---

api/public_api_v1.yaml
lib/api/public_api_v1.ts
lib/controllers/messages.ts
lib/utils/response.ts

when submitMessage success:
- specs say 201 (not 202) when 
- refactor: returns message id instead of empty object

fix: align api to specs

---

api/public_api_v1.yaml
lib/api/public_api_v1.ts

Quando un developer si iscrive alle API, non è ancora autorizzato ad usare la funzione `default_address`, per cui togliamolo dall'esempio di base dell'API.

fix: removed default_address from submit message example

---

deploy.cmd

using npm results in failed deployment:
`Module '"D:/home/site/wwwroot/node_modules/ulid/index"' resolves to a non-module entity and cannot be imported using this construct.`
with yarn everything works. 
accidentally, it's fixed in production atm as I once ran yarn install from kudu console.

chore: use yarn instead of npm

---

lib/created_message_queue_handler.ts
lib/utils/strings.ts
package.json
yarn.lock

As with https://github.com/teamdigitale/digital-citizenship-functions/pull/111
I'm trying to reuse the model layer of this repository importing it to another one:
`yarn add  https://github.com/teamdigitale/digital-citizenship-functions`
Some oddities with ulid 1.x module causes errors using it with Typescript 
so I suggest to upgrade to 2.x which is a better citizen.
`node_modules/digital-citizenship-functions/lib/utils/strings.ts(2,23): error TS2497: Module '.../digital-citizenship/node_modules/ulid/index"' resolves to a non-module entity and cannot be imported using this construct.
`

chore: use ulid 2.x

---

lib/utils/documentdb_model_versioned.ts

[#153367500]
the unversioned find() method does not return an error when the document is not found.
backported the same behavior in findLastVersionByModelId()

fix: do not return error on 404 not found in findLastVersionByModelId

---

lib/controllers/adm/services.ts
lib/controllers/messages.ts
lib/controllers/profiles.ts
lib/utils/__tests__/request_middleware.test.ts
lib/utils/middlewares/azure_api_auth.ts
lib/utils/middlewares/azure_user_attributes.ts
lib/utils/middlewares/context_middleware.ts
lib/utils/middlewares/required_param.ts
lib/utils/request_middleware.ts
lib/utils/response.ts

While I was writing an article describing the technique we implemented, I realized the code I wrote wasn't correct, `IResponse` was defined with the `kind` attribute of type `string` when instead the `kind` attribute has the type that names the kind of response (e.g. `IResponseNotFound`), `IResponse` should have a type parameter that is the type of `kind`.

Fix IResponse types

---

lib/utils/request_middleware.ts

@cloudify I was reading your [post](http://federicoferoldi.com/2017/12/28/using-the-typescript-type-system-to-validate-express-handlers.html) and noticed a possible issue: I think that the type parameter `RH` should be moved to the right
```ts
// current signature
declare function withRequestMiddlewares<RH, R1, R2, T1, T2>(
m1: IRequestMiddleware<R1, T1>,
m2: IRequestMiddleware<R2, T2>
): (handler: (v1: T1, v2: T2) => Promise<IResponse<RH>>) => RequestHandler<RH | R1 | R2>
declare const m1: IRequestMiddleware<'R1', 'T1'>
declare const m2: IRequestMiddleware<'R2', 'T2'>
declare const handler: (v1: 'T1', v2: 'T2') => Promise<IResponse<'RH'>>
// const x: (req: Request) => Promise<IResponse<{} | "R1" | "R2">>
const x = withRequestMiddlewares(m1, m2)(handler)
```
Note the inferred type `{}` …

Fix withRequestMiddlewares signatures

---

api/public_api_v1.yaml

Error responses in profile update definitions lacks of schema. Without the schema the autorest utility fails to create a correct api client

Add schema to api Swagger definitions for profile update

---

host.json
lib/__tests__/created_message_queue_handler.test.ts
lib/__tests__/emailnotifications_queue_handler.test.ts
lib/created_message_queue_handler.ts
lib/emailnotifications_queue_handler.ts
lib/types/json.d.ts
lib/utils/__tests__/azure_queues.test.ts
lib/utils/azure_queues.ts
lib/utils/errors.ts

Work in progress for https://www.pivotaltracker.com/story/show/150597257
We can re-schedule a message in the queue for later processing using visibilityTimeout.
Two possible retry stategies: 
1. **update** the visibilityTimeout of the received message then put it again in the queue. this strategy use the `dequeCount` property in Functions bindings and calls `context.done(err)` to return the message to the queue. after 7 days the message will be deleted from the queue in any case.
2. **create** a new message in the queue with the computed visibilityTimeout. this strategy does not rely on `dequeCount` (as it's always = 1) and calls `context.done()` to remove the old message from the queue. the number of retries is saved in the message payload.
- when maxDequeCount will be reached the …

[#150597257] - schedule retries when a queue action fails

---

lib/utils/types.ts

this is a better enum type than the actual one, as this one is statically checked
while actually you can create objects with a wrong enum key and it only fails at runtime
ref. https://github.com/gcanti/io-ts/issues/67#issuecomment-368068197

refactor: enum types

---

__mocks__/superagent.ts
lib/utils/__tests__/mailup.test.ts
package.json
yarn.lock

It looks like superagent-mock does not work with promises as it expects the metehod end() to be called.
As we don't want to fallback to old style callbacks, it's necessary to provide a custom superagent mock implementation. An alternative is to fake NodeJS http requests at a lower level with something like https://github.com/node-nock/nock

[#155679212] fix superagent mock and avoid jest tests to stuck

---

api/definitions.yaml
gulpfile.js
lib/__tests__/created_message_queue_handler.test.ts
lib/__tests__/emailnotifications_queue_handler.test.ts
lib/api/admin_api.ts
lib/api/definitions/CreatedMessageWithContent.ts
lib/api/definitions/CreatedMessageWithoutContent.ts
lib/api/definitions/NewMessage.ts
lib/api/definitions/TimeToLiveSeconds.ts
lib/api/public_api_v1.ts
lib/controllers/__tests__/messages.test.ts
lib/controllers/messages.ts
lib/created_message_queue_handler.ts
lib/emailnotifications_queue_handler.ts
lib/models/__tests__/created_message_event.test.ts
lib/models/__tests__/message.test.ts
lib/models/__tests__/notification_event.test.ts
lib/models/created_message_event.ts
lib/models/message.ts
lib/models/notification_event.ts
lib/utils/__tests__/azure_queues.test.ts
lib/utils/azure_queues.ts
lib/utils/errors.ts

Between the main changes, note that with this PR [the whole Message is passed in the NotificationEvent](https://github.com/teamdigitale/digital-citizenship-functions/pull/158/files#diff-369872c88999ee654209f0771aaa8f25R129) (queue) while actually we pass only some fields:
- added two fields (createAt, timeToLive) to the MessageModel
- added a type (NotExpiredMessage) that checks that Date.now() < createdAt + timeToLive
- update notification status in case of error / expire
- refactor queue handlers to simplify error handling (ie. avoid try / catch blocks in index, pushed error logging at the end of the index method) and avoiding calling context.done (return a promise instead)

[#150588117] WIP added time to live check to email notification handler

---

api/definitions.yaml
api/public_api_v1.yaml
lib/__tests__/created_message_queue_handler.test.ts
lib/__tests__/emailnotifications_queue_handler.test.ts
lib/controllers/__tests__/messages.test.ts
lib/controllers/messages.ts
lib/created_message_queue_handler.ts
lib/emailnotifications_queue_handler.ts
lib/models/__tests__/message.test.ts
lib/models/__tests__/message_status.test.ts
lib/models/__tests__/notification_status.test.ts
lib/models/message_status.ts
lib/models/notification_status.ts
lib/public_api_v1.ts
lib/utils/errors.ts

- added versioned message status model
- update message status in the message queue handler
- the getmessage controller now returns message status aside notification status
Shape of a message:
```
{
"message": {
"content": {
"markdown": "...",
"subject": "..."
},
"fiscal_code": "ZERTHB99A45Y149X",
"id": "01C8RHV61QBX82GSWYQ1VFNBN5",
"sender_service_id": "5a25"
},
"notification": {
"email": "SENT_TO_CHANNEL"
},
"status": "PROCESSED" <------
}
```

[#150737636] add message status

---

lib/controllers/__tests__/messages.test.ts
lib/utils/request_middleware.ts

Actually there's a bug in promise handling (tests do not await). 
This PR fixes this beahvior. Now the express request handler returns the promise so we can wait in tests.

[#155970981] fix wait for promises in tests

---

.gitignore
gulpfile.js
package.json
webpack.config.js
yarn.lock

the actual build fails with 
`Exception while executing function: Functions.AdminApi -> One or more errors occurred. -> TypeError: require is not a function\n`
this fixes an error with funcpack + modules that "gently" hijacks require, see
https://github.com/felixge/node-formidable/issues/337

[#156379054] fix funcpack build with custom webpack config

---

CHANGELOG.md
api/definitions.yaml
lib/controllers/__tests__/messages.test.ts
lib/controllers/messages.ts

- Exposes "created_at" with message payload in GetMessage(s) controllers
- Fix some required fields in API definitions

[#157284546] expose message creation date

---

api/definitions.yaml
lib/__tests__/created_message_queue_handler.test.ts
lib/controllers/__tests__/messages.test.ts
lib/controllers/profiles.ts
lib/created_message_queue_handler.ts
lib/models/profile.ts
lib/types/url.d.ts
package.json
yarn.lock

- adds a new property "blocked_channels" to the profile model 
`{ serviceId: [ array of blocked channels ]}`
- adds logic to skip blocked channel into created_message_queue_handler
profile model: 
```
{
"blocked_channels": {
"5a25abf4fcc89605c082f042c49a": [
"EMAIL",
"WEBHOOK"
]
},
"email": "xxxxxxxxx@xxxxxxx.com",
"is_inbox_enabled": true,
"is_webhook_enabled": true,
"preferred_languages": [
"it_IT"
],
"version": 46
}
```
There at least are a couple of possible implementation. The one in "Scenario 1" is implemented in the current PR.
We block notifications in the `created_message_queue_handler`, before dispatching the messages to the channel queue handlers.
**Pros**: efficient as it avoids to send notifications to the channels queue handlers
**Cons**: there are some chances that the …

[#157387718] WIP: service blacklist

---

lib/__tests__/webhook_queue_handler.test.ts
lib/webhook_queue_handler.ts

trigger a retry in case of HTTP 5xx errors. 
added tests

[#157917582] return transient error in case the API proxy returns 5xx HTTP status

---

lib/created_message_queue_handler.ts
lib/emailnotifications_queue_handler.ts
lib/models/__tests__/message.test.ts
lib/models/__tests__/notification.test.ts
lib/models/__tests__/profile.test.ts
lib/models/message.ts
lib/models/message_status.ts
lib/models/notification.ts
lib/models/profile.ts
lib/models/service.ts
lib/public_api_v1.ts
lib/utils/__tests__/documentdb.test.ts
lib/utils/documentdb.ts
lib/utils/documentdb_model_versioned.ts
lib/webhook_queue_handler.ts

Force all CosmosDb queries to provide a partitionKey.
This is important as the current implementation of iteratorToArray (and so ResponseSuccessIterator) swallows any error regarding cross partition queries.

[#158006232] forces the use of a partitionKey during queries

---

lib/__tests__/created_message_queue_handler.test.ts
lib/__tests__/emailnotifications_queue_handler.test.ts
lib/__tests__/webhook_queue_handler.test.ts
lib/controllers/__tests__/messages.test.ts
lib/controllers/messages.ts
lib/created_message_queue_handler.ts
lib/emailnotifications_queue_handler.ts
lib/public_api_v1.ts
lib/utils/__tests__/application_insights.test.ts
lib/utils/application_insights.ts
lib/utils/azure_queues.ts
lib/webhook_queue_handler.ts

Added tracking of:
for each queue handler:
- number of TransientErrors (retry) + time elapsed from message creation
- number of PermanentErrors + time elapsed from message creation
- number of Sucessful processing + time elapsed from message creation
- duration of calls to email provider (and failures)
- duration of calls to webhook endpoint (and failures)
that would be useful to monitor queues lenght as well, but that would require a dedicated function.

[#151202533] add telemetry and insights

---

QueueMonitor/function.json
host.json
lib/index.ts
lib/queue_monitor.ts
lib/utils/azure_queues.ts

Runs every 30 seconds to store queue length into Application Insights metrics:

[#157928027] add a function to monitor queue length 

---

api/definitions.yaml
lib/controllers/__tests__/profiles.test.ts
lib/controllers/profiles.ts

we do not return the sender_allowed flag with full profile as with a full profile we got the whole array with blocked services

[#158179629] feat: return sender_allowed with limited profile

---

ProfileEventsQueueHandler/function.json
PublicApiV1/function.json
api/public_api_v1.yaml
host.json
lib/controllers/__tests__/profiles.test.ts
lib/controllers/profiles.ts
lib/index.ts
lib/profile_events_queue_handler.ts
package.json
yarn.lock

Reacts to messages sent to the ProfileEvents queue with one catch-all handler.
Calls the API (`submitMessageForUser`) through an HTTP request using the API-Key of the service associated to the app backend to send the welcome message.
I'd like to implement [1] using `request` method from italia-ts-commons bus in order to do that I miss the ability to add custom HTTP headers as RequestHeadersKeys are actually hardcoded.
WIP as it lacks tests.

[#157244655] send welcome message

---

templates/mjml/default.mjml

This PR aims to fix wrong line-height for any heading within `contentHtml` HTML:
As `${contentHtml}` HTML comes from Markdown and it can't be styled, we had to prevent any styling coming from its containing tags.
Due to this, I removed the global `<mj-text ...>` attribute causing its rules to be applied to any `<mj-text>` content.

Fixing styling for email's inner message.

---

api/definitions.yaml
lib/__tests__/created_message_queue_handler.test.ts
lib/__tests__/emailnotifications_queue_handler.test.ts
lib/__tests__/webhook_queue_handler.test.ts
lib/controllers/__tests__/messages.test.ts
lib/controllers/messages.ts
lib/created_message_queue_handler.ts
lib/emailnotifications_queue_handler.ts
lib/models/__tests__/created_message_event.test.ts
lib/models/__tests__/notification_event.test.ts
lib/models/created_message_event.ts
lib/models/message.ts
lib/models/notification_event.ts
lib/utils/__tests__/documentdb.test.ts
lib/utils/azure_queues.ts
lib/utils/documentdb.ts
lib/utils/errors.ts
lib/webhook_queue_handler.ts

This PR introduces:
1. a pending flag on the message metadata that gets used to filter out from the result of `getMessages` the messages that are being processed (or have been rejected)
1. a new `REJECTED` status for messages that have been rejected due to a non-existent profile or a blocked sender
TODO:

[#165905031] getMessages should not return rejected messages 

---

api/admin_api.yaml
api/public_api_v1.yaml

- `admin_api.yaml` it's not correct. see this: [swagger.editor.io](http://editor.swagger.io/?url=https://raw.githubusercontent.com/teamdigitale/io-functions/master/api/admin_api.yaml).
this is correct:
```
definitions:
Service:
$ref: "definitions.yaml#/Service"
```
this is not:  
```
definitions:
$ref: "definitions.yaml"
```
- `public_api_v1_yaml` and `admin_api.yaml` do not have references all the schemas used in definitions; and `io-utils` (dependency used in io-functions) dereference all the found schemas, thus losing the relationships between the generated classes.
Reference all used schemas under definitions all the schemas and sub-schemas used by the specification. 
example: 
```
definitions:
Service: 
$ref: "definitions.yaml#/Service"
Name: 
$ref: "definitions.yaml#/Name"
```

Fixes Swagger 2.0 Specs

---

lib/profile_events_queue_handler.ts

This PR fix the below typo error:

[#166536717] Typo error in welcome message
