lib/controllers/__tests__/profiles.test.ts
lib/controllers/messages.ts
lib/controllers/profiles.ts
lib/public_api_v1.ts
lib/utils/__tests__/request_middleware.test.ts
lib/utils/either.ts
lib/utils/error_handler.ts
lib/utils/fiscalcode_middleware.ts
lib/utils/middlewares/context_middleware.ts
lib/utils/middlewares/required_id_param.ts
lib/utils/middlewares/required_param.ts
lib/utils/request_middleware.ts
lib/utils/response.ts

With this approach we can declare exactly what types an HTTP handler
expects as input and what types are expected as output. The compiler
will enforce this definition.

Implements wrappers to handle requests and responses in a type safe way.

---

lib/controllers/__tests__/profiles.test.ts
lib/controllers/debug.ts
lib/controllers/messages.ts
lib/controllers/profiles.ts
lib/public_api_v1.ts
lib/utils/middlewares/__tests__/azure_api_auth.test.ts
lib/utils/middlewares/__tests__/azure_user_attributes.test.ts
lib/utils/middlewares/__tests__/fiscalcode.test.ts
lib/utils/middlewares/azure_api_auth.ts
lib/utils/middlewares/azure_user_attributes.ts
lib/utils/middlewares/fiscalcode.ts
lib/utils/request_middleware.ts

Also adds lookup of organization associated to users through
custom attributes in the Azure API Management portal.

Adds support for authorizing endpoints based on groups.

---

.gitignore

**local.* is for local settings when running azure functions locally
*js.map are generated from typescript when using sourceMaps (should be added to tsconfig.json)

chore: added entries in gitignore

---

api/messages.yaml
api/templates/model.ts.njk
lib/__tests__/created_message_queue_handler.test.ts
lib/api/definitions/BodyLong.ts
lib/api/definitions/BodyShort.ts
lib/api/definitions/CreatedMessage.ts
lib/api/definitions/EmailAddress.ts
lib/api/definitions/FiscalCode.ts
lib/api/definitions/HttpStatusCode.ts
lib/api/definitions/MessageContent.ts
lib/api/definitions/MessageStatus.ts
lib/api/definitions/NewMessage.ts
lib/api/definitions/NewMessageDefaultAddresses.ts
lib/api/definitions/PaginationResponse.ts
lib/api/definitions/ProblemJson.ts
lib/api/definitions/TimeToLive.ts
lib/controllers/__tests__/messages.test.ts
lib/controllers/messages.ts
lib/created_message_queue_handler.ts
lib/emailnotifications_queue_handler.ts
lib/models/created_message_event.ts
lib/models/notification.ts
lib/models/profile.ts
lib/utils/middlewares/azure_api_auth.ts
lib/utils/response.ts
lib/utils/strings.ts
lib/utils/tuples.ts
package.json
yarn.lock

[#150801764] Adds default email address when sending a message

---

api/generate_models.ts
api/public_api_v1.yaml
api/templates/model.ts.njk
lib/api/definitions/BodyLong.ts
lib/api/definitions/BodyShort.ts
lib/api/definitions/CreatedMessage.ts
lib/api/definitions/FiscalCode.ts
lib/api/definitions/HttpStatusCode.ts
lib/api/definitions/MessageContent.ts
lib/api/definitions/MessageStatus.ts
lib/api/definitions/NewMessage.ts
lib/api/definitions/NewMessageDefaultAddresses.ts
lib/api/definitions/PaginationResponse.ts
lib/api/definitions/Preferences.ts
lib/api/definitions/PreferredLanguages.ts
lib/api/definitions/ProblemJson.ts
lib/api/definitions/TimeToLive.ts
package.json
yarn.lock

also adds prettifying to generated code

[#150783596] Adds models and specs for preferences

---

gulpfile.js
package.json
yarn.lock

fix: use gulp-run instead of gulp-exec

---

lib/controllers/profiles.ts
package.json

fixes a nasty exception escapes from middleware when request.body is empty or email is undefined.

Fix upsert profile

---

api/public_api_v1.yaml
lib/api/public_api_v1.ts

- added examples to swagger specs
- added upsert profile endpoint to specs
- renamed sender_organization_id to sender_service_id

chore: added examples to api spec

---

lib/api/public_api_v1.ts

fix: api specs examples

---

lib/admin_api.ts
lib/created_message_queue_handler.ts
lib/emailnotifications_queue_handler.ts
lib/openapi.ts
lib/public_api_v1.ts

https://www.pivotaltracker.com/story/show/150777493

[#150777493] set logging level from env

---

api/definitions.yaml
api/templates/macros.njk
api/templates/model.ts.njk
lib/api/admin_api.ts
lib/api/definitions/ProblemJson.ts
lib/api/definitions/TimeToLive.ts
lib/api/public_api_v1.ts
lib/controllers/__tests__/messages.test.ts
lib/utils/default.ts

calling t.validate() sets default values

[#151203322]: feat: added default values from openapi specs

---

lib/__tests__/created_message_queue_handler.test.ts
lib/__tests__/emailnotifications_queue_handler.test.ts
lib/controllers/__tests__/messages.test.ts
lib/controllers/__tests__/profiles.test.ts
lib/controllers/adm/__tests__/services.test.ts
lib/controllers/messages.ts
lib/created_message_queue_handler.ts
lib/models/__tests__/created_message_event.test.ts
lib/models/__tests__/message.test.ts
lib/models/__tests__/notification.test.ts
lib/models/__tests__/notification_event.test.ts
lib/models/__tests__/profile.test.ts
lib/models/__tests__/service.test.ts
lib/utils/__tests__/documentdb.test.ts
lib/utils/__tests__/response.test.ts
lib/utils/documentdb_model_versioned.ts
lib/utils/middlewares/__tests__/azure_user_attributes.test.ts
lib/utils/strings.ts
package.json
tslint.json

Stricter rules, also fixed `wait`s on non-Promise values

Tslint updates

---

package.json
yarn.lock

see https://github.com/gcanti/io-ts/issues/8

[#153872395] Update io-ts package

---

lib/utils/middlewares/__tests__/client_ip_middleware.test.ts

fix unhandled exception in client ip middleware tests
(reminder: always return a promise in async jest tests :)

[#154050923] - fix: client ip middleware tests

---

api/definitions.yaml
api/public_api_v1.yaml
lib/api/admin_api.ts
lib/api/definitions/CreatedMessageWithContent.ts
lib/api/definitions/CreatedMessageWithoutContent.ts
lib/api/definitions/MessageResponseWithContent.ts
lib/api/definitions/MessageResponseWithoutContent.ts
lib/controllers/__tests__/messages.test.ts
lib/controllers/messages.ts
package.json

I've also removed the "title" property from some definitions as it was useless.

[#154516753] - added definition for message without content

---

api/public_api_v1.yaml

Hot fix for YAML api specs (CreatedMessage -> CreatedMessageWithoutContent)

Hot fix for YAML api specs

---

lib/__tests__/emailnotifications_queue_handler.test.ts
lib/emailnotifications_queue_handler.ts
lib/types/nodemailer-sendgrid-transport.d.ts
lib/utils/mailup.ts
package.json

this cannot work in production until the orded is committed, but it's fine fot test environment.

[#152800384] replace sendgrid with mailup

---

lib/__tests__/created_message_queue_handler.test.ts
lib/created_message_queue_handler.ts

because option as arguments are code smells

[#156484880] refactor: avoid taking option as arguments in functions

---

CHANGELOG.md

rendered: https://github.com/teamdigitale/digital-citizenship-functions/blob/156498236-changelog/CHANGELOG.md

[#156498236] add a changelog

---

gulpfile.js

ie. 
`RELEASE=patch gulp:release`

[#156503329] added semver release argument to the gulp release procedure

---

gulpfile.js
lib/types/mjml.d.ts
package.json
templates/mjml/default.mjml
yarn.lock

updated template file syntax according to new mjml specs

updated mjml dep

---

lib/utils/__tests__/documentdb.test.ts
lib/utils/__tests__/documentdb_model.test.ts
lib/utils/documentdb.ts
lib/utils/documentdb_model.ts

Added method to upsert mutable models.

[#157996274] added createOrUpdate method to models

---

api/definitions.yaml
lib/controllers/profiles.ts
lib/models/__tests__/profile.test.ts
lib/models/profile.ts

in user profile we'll have
```
terms_of_service_accepted: {
"someServiceId1": <numeric version>,
"someServiceId2": <numeric version>,
...
}
```

[#158073462] add terms of service to Services and accepted ToS in user's Profile

---

api/definitions.yaml
lib/controllers/profiles.ts
lib/models/__tests__/profile.test.ts
lib/models/profile.ts

removes AcceptedServiceTosVersion from profile

[#158284310] revert tos in profile

---

api/definitions.yaml
lib/controllers/__tests__/messages.test.ts
lib/controllers/__tests__/services.test.ts
lib/controllers/adm/__tests__/services.test.ts
lib/controllers/adm/services.ts
lib/controllers/messages.ts
lib/models/__tests__/service.test.ts
lib/models/service.ts
lib/utils/middlewares/__tests__/azure_user_attributes.test.ts

0 is default
wip as it lacks some tests but logic is complete

[#158496486] limit payment amount for each service

---

api/public_api_v1.yaml

Adds more documentation about messages and the verification flow

Updates public API specs.

---

api/definitions.yaml
lib/controllers/__tests__/messages.test.ts
lib/controllers/messages.ts

saves payment_data aside markdown and subject

[#158906138] save payment-data

---

ProfileEventsQueueHandler/function.json
lib/__tests__/profile_events_queue_handler.test.ts
lib/profile_events_queue_handler.ts

- renames environment variables
- adds tests
- disables the function (until we have a content for the welcome message) so we can deploy the new functions

[#157244655] fixes to welcome message

---

lib/controllers/services.ts
lib/models/visible_service.ts

fixes mismatch between api specs and visible service type

fix: visible service type

---

lib/created_message_queue_handler.ts

fixes logic handling blocked inbox or channels

fix: hotfix for undefined value

---

api/definitions.yaml
lib/controllers/__tests__/profiles.test.ts
lib/controllers/profiles.ts

make version, is_inbox_enabled and is_webhook_enabled required into profile

[#159490074] make fields required

---

lib/profile_events_queue_handler.ts

we must take a decision on how the internal links work with emails

change default welcome message text

---

templates/mjml/default.mjml

Modifiche fatte in accordo con @matteodesanti, con cui abbiamo concordato anche di commentare il codice per Header e Footer, in quanto non ancora usati.

Email layout review with icons on top

---

gulpfile.js
lib/controllers/__tests__/messages.test.ts
lib/controllers/__tests__/services.test.ts
lib/utils/__tests__/response.test.ts
lib/utils/response.ts
package.json
yarn.lock

- fix uncommitted yarn.lock
- prettify email template
- fix IResponseSuccessJsonIterator return value

fix master build and tests

---

api/definitions.yaml
lib/controllers/__tests__/services.test.ts

Add missing required attributes.

Fix ServiceTuple and ServicePublic definitions

---

api/definitions.yaml
lib/__tests__/profile_events_queue_handler.test.ts
lib/controllers/__tests__/profiles.test.ts
lib/controllers/profiles.ts
lib/models/__tests__/profile.test.ts
lib/models/profile.ts

[#163190244] L'accettazione dei Terms of Service va salvata nel profilo dell'utente

[#163190244] Adds accepted ToS version to user profile

---

api/public_api_v1.yaml

[#161886901]- Implement 429 return code.

[#161886901] - Implement 429 return code.

---

api/public_api_v1.yaml

[#157896066] - Implement 429 return code.
